name: Development Workflow

on:
  push:
    branches: [ main, develop, "claude-code/*" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and test in container
        run: |
          echo "Setting up containerized environment..."
          
          # Install system dependencies
          apt-get update
          apt-get install -y curl wget build-essential
          
          # Install Super library
          cd /tmp
          echo "Downloading Super library..."
          wget -v https://github.com/brimdata/super/releases/latest/download/super-linux-amd64.tar.gz
          echo "Extracting Super library..."
          tar -xzf super-linux-amd64.tar.gz
          echo "Installing Super library..."
          mv super-linux-amd64/super /usr/local/bin/
          chmod +x /usr/local/bin/super
          echo "Verifying Super installation..."
          super --version
          
          # Install Python dependencies
          cd $GITHUB_WORKSPACE
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          
          # Run tests
          if [ -d "tests" ]; then
            python -m pytest tests/ -v --cov=src --cov-report=xml
          else
            echo "No tests directory found"
          fi

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: success()

  validate-sam:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/sam/build-python3.11:latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate SAM template
        env:
          AWS_DEFAULT_REGION: us-east-1
          SAM_CLI_TELEMETRY: 0
        run: |
          if [ -f "template.yaml" ]; then
            sam validate --region us-east-1
          else
            echo "No SAM template found"
          fi